
name: Firebase Continous Deployment

on:
  push:
    branches: 
      - master

jobs:
  post_slack_message:
    runs-on: ubuntu-latest
    steps:
      - uses: rtCamp/action-slack-notify@v2.0.0
    env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNMAE: 30lmas09
        SLACK_CHANNEL: try1
